### ISSUE TITLE
Issue importing package - "Cannot read property 'style' of  undefined"

### ISSUE THREAD

**Issue by rossmartin** [MrToph/react-native-countdown-circle#1]
Hey thanks for this awesome component.  I have to comment out [line 87 of index.js](https://github.com/MrToph/react-native-countdown-circle/blob/master/src/index.js#L87) to get my app to run when importing `react-native-countdown-circle`.  If I don't comment out this line I see this below - 

![image](https://cloud.githubusercontent.com/assets/2498502/26207557/7f167fd2-3bad-11e7-9269-f0146d30d513.png)

I'm using react-native 0.43.3 and react 16.0.0-alpha-6

**Comment by MrToph** [comment]
Yes, it uses the new `ViewPropTypes` which only exist in `react-native 0.44.x` as `View.propTypes` is deprecated. But you're right, the majority is probably still running an older version of react-native and it's a good idea to support older versions as well. I'll push a new release in a minute.

Thanks for pointing that out.

**Comment by MrToph** [comment]
New version released, can you try it?

**Comment by rossmartin** [comment]
Its fixed in 1.0.2, thank you 🍻
