### ISSUE TITLE
In IOS Circular Animation is not good 

### ISSUE THREAD

**Issue by ronakupadhyay123** [MrToph/react-native-countdown-circle#27]
Hi 

Help me Circle Animation is not looking good. See below image

![IMG-0308](https://user-images.githubusercontent.com/52035172/63419414-67becb00-c422-11e9-844b-b01796322985.jpg)

**Comment by tcainne** [comment]
Same for me ...

**Comment by tcainne** [comment]
Thank a lot !



Le jeu. 22 août 2019 à 13:13, ronakupadhyay123 <notifications@github.com> a
écrit :

**Comment by caglardurmus** [comment]
> Hi @tcainne
> 
> I got solution please open dependancy index.js file in node module..
> 
> and add == >> overflow: "hidden",
> to "outerCircle" in styles
> 
> outerCircle: {
> overflow: "hidden",
> justifyContent: "center",
> alignItems: "center",
> backgroundColor: "#e3e3e3"
> },

Thanks! I hope it will fixed soon
