### ISSUE TITLE
I want to restart at will.

### ISSUE THREAD

**Issue by Harkindey** [MrToph/react-native-countdown-circle#6]
I need to restart the countdown without changing the seconds.

**Comment by MrToph** [comment]
Good idea, thanks for the contribution, Just see my comment at your PR about the implementationm details

**Comment by mustafakucuk** [comment]
I solved it like this

I added

`  restartCount(nextProps){
    this.setState(getInitialState(this.props), this.restartAnimation)
  }
`
in
**react-native-countdown-circle/src/index.js**

and

`          <CountdownCircle
            ref = {ref => this.countdown = ref}
           ...
`
I can use.

`this.countdown.restartCount();`

**Comment by MrToph** [comment]
You don't need the `nextProps` argument, but that's how I imagined it :+1:

If you like, you can create a PR

**Comment by Harkindey** [comment]
@mustafakucuk will be expecting your PR

**Comment by foxdreamstudio** [comment]
@mustafakucuk i cant implement that, can you show me how to do this with real example maybe

**Comment by MrToph** [comment]
The recommended way to do this is by setting a different `key` as this will completely remove and remount the component. See [React Blog](https://reactjs.org/blog/2018/06/07/you-probably-dont-need-derived-state.html) for this pattern.
