### ISSUE TITLE
Can we change the animation of circle according to time elapsed?

### ISSUE THREAD

**Issue by dverma4u** [MrToph/react-native-countdown-circle#8]
Currently the animation is completing it's rotation with every second. But i want to use it in such a way to animate the circle with every second elapsed 
for example - i want the circle to complete it rotation in 60 seconds not in 1 sec.
Can anybody please help me doing that?

**Comment by MrToph** [comment]
This is a new feature request in my opinion. My use-case was to have the circle tick in 1 second intervals and change the text according to it. I still think this is the more desired use-case, so I won't add your feature.

Having said that, you can fork it and adjust the logic yourself. It should be quite easy, you need to change the `duration` in the `restartAnimation` function.

**Comment by dverma4u** [comment]
@MrToph now the time(text) is decreasing after one complete animation. Is there any way by which we can decrease the time with every second elapsed?

**Comment by dverma4u** [comment]
getting this error when using `updateText` props 

![capture](https://user-images.githubusercontent.com/31440793/37342088-8f472884-26e9-11e8-84be-0f7f5f97bd25.JPG)
![capture22](https://user-images.githubusercontent.com/31440793/37342089-8f97db80-26e9-11e8-9d11-5dfb000f6f21.JPG)

**Comment by MrToph** [comment]
I guess you're talking about the text. You need to create a second timer / setInterval that ticks every second, takes track of the time, calls the `updateText` prop and sets the new text with `setState`

**Comment by muhizia** [comment]
I have the same issue but I can fig out what you saying #MrToph
